### ISSUE TITLE
sdefl_compress reads past the bounds of the input array

### ISSUE THREAD

**Issue by zeux** [vurtun/lib#33]
In this code:

```
      while (run-- != 0) {
        unsigned h = sdefl_hash32(&in[i]);
```

sdefl_hash32 triggers an access violation when there's less than 4 bytes left until the end of input, and the array is on a page boundary. This change fixes it but I'm not sure it's correct to just skip the hash:

```
        unsigned h = (i + 4 <= in_len) ? sdefl_hash32(&in[i]) : 0;
```

There's similar code in `sdefl_fnd` but that - as far as I can tell - is safe since it's only ever called with an offset that's far enough away from the end of input, as long as `SDEFL_MIN_MATCH` is at least 3.

**Comment by vurtun** [comment]
At least in terms of compression correctness the out of bounds read and hash table modification has no effect since it only happens at the end and no matches can be generated for these positions. 

Still the out of bounds read should be fixed, but I am not sure of the fix. Introducing a condition here is a bit hefty given that the condition only applies for the last 4 bytes of input. Especially since for the last few bytes the whole loop doesn't need to be run at all. Maybe there is a way to use `run` and `inc` to skip the loop entirely.

**Comment by zeux** [comment]
Something like this perhaps? This seems to work.

```
      int run_inc = run * inc;
      if (in_len - (i + run_inc) > SDEFL_MIN_MATCH) {
        while (run-- != 0) {
          unsigned h = sdefl_hash32(&in[i]);
          s->prv[i&SDEFL_WIN_MSK] = s->tbl[h];
          s->tbl[h] = i, i += inc;
        }
      } else {
        i += run_inc;
      }
```

**Comment by vurtun** [comment]
Thanks I tried your solution and out of bounds seems to work as well for my test files. Also tried a few other alternatives but they all turned out too complex.
